#ifndef TOYZK80_CONDITION_INSTRUCTION_H
#define TOYZK80_CONDITION_INSTRUCTION_H

#define INSTRUCTION_CP_R(R) void instruction_CP_##R();
void instruction_CP_HLp();
void instruction_CP_n();

#define DEFINE_CONDITION_INSTRUCTION(R)\
    INSTRUCTION_CP_R(R);     \

DEFINE_CONDITION_INSTRUCTION(B)
DEFINE_CONDITION_INSTRUCTION(C)
DEFINE_CONDITION_INSTRUCTION(D)
DEFINE_CONDITION_INSTRUCTION(E)
DEFINE_CONDITION_INSTRUCTION(H)
DEFINE_CONDITION_INSTRUCTION(L)
DEFINE_CONDITION_INSTRUCTION(A)


#ifdef DEBUG
void test_instruction_condition();
#endif

#undef INSTRUCTION_CP_R
#undef DEFINE_CONDITION_INSTRUCTION
#endif  // TOYZK80_CONDITION_INSTRUCTION_H
